site_name: Data Style Guide
site_description: Standards for tables, charts, maps and data formatting for Business News (print & online)
site_url: https://business-news.github.io/data-style-guide
repo_url: https://github.com/business-news/data-style-guide

theme:
  name: material
  # custom_dir: overrides      # ← keep removed/commented out
  logo: assets/logo.svg
  favicon: assets/favicon.svg
  palette:
    - scheme: default
      primary: custom
      accent: custom
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - search.suggest
    - content.code.copy
    - navigation.footer

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/business-news/data-style-guide
      name: Source on GitHub
  footer: |
    <div class="bn-footer-extra">
      <span>© {{ now().year }} Business News</span>
      <span class="bn-sep">•</span>
      <a href="https://www.businessnews.com.au" target="_blank" rel="noopener">businessnews.com.au</a>
      <span class="bn-sep">•</span>
      <a href="mailto:general@businessnews.com.au">general@businessnews.com.au</a>
    </div>

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - attr_list

nav:
  - Home: index.md
  - Colour Palettes: colour-palettes.md
  - Charts: charts.md
  - Tables: tables.md
  - Number Formatting: number-formatting.md
  - Accessibility: accessibility.md
  - Production Checklist: production-checklist.md
